### ISSUE TITLE
Error in window.createLemonSqueezy()

### ISSUE THREAD

**Issue by sulaimanwebdev** [lmsqueezy/lemonsqueezy.js#52] opened 2024-02-04 14:15 UTC
I downloaded the Lemon Squeezy Next JS billing repo. Everything work perfectly, but I get this error when I run the app it says TypeError: window.createLemonSqueezy is not a function

The error is in /components/plan.jsx

How can I fix this error?

<img width="959" alt="Screenshot 2024-02-04 at 7 00 30 PM" src="https://github.com/lmsqueezy/lemonsqueezy.js/assets/74793541/28ad1271-28bb-4c9d-96c4-70b9af1aafc8">

**Comment by bmackio** [comment] 2024-02-18 16:07
The docs on checkout overlay and `window.createLemonSqueezy()` are really spare.

https://docs.lemonsqueezy.com/help/developers/checkout-overlay

I'm investigating how to use the overlay, but the instructions are neither clear or complete.

**Comment by bmackio** [comment] 2024-02-18 16:20
For example: the image on this docs page is not showing up:
<img width="1463" alt="Screenshot 2024-02-18 at 11 19 17 AM" src="https://github.com/lmsqueezy/lemonsqueezy.js/assets/1240213/f529e01a-6485-47af-9e9a-640f2d27feb2">

**Comment by newme616** [comment] 2024-02-18 16:50
I got weird problems in incognito mode with this were lemonsqueezy doesn't load

**Comment by bmackio** [comment] 2024-02-18 17:00
Interesting! Another weirdness is that I am able to `import * as ls from'@lemonsqueezy/lemonsqueezy.js'`

And gain direct access to 
```
const checkout = await ls.createCheckout({
      storeId: process.env.LEMONSQUEEZY_STORE_ID,
      variantId: res.variantId,
      attributes
```
Without the need to:
```
const ls = new LemonSqueezy(process.env.LEMONSQUEEZY_API_KEY as string)
```
When I try to initialize the constructor above I get an error:
```
TypeError: _lemonsqueezy_lemonsqueezy_js__WEBPACK_IMPORTED_MODULE_1__.default is not a constructor
```
I'm trying to get a custom overlay, so sorry to hijack your issue.

------
related to your issue, are you inserting `<script 
          src="https://app.lemonsqueezy.com/js/lemon.js" 
          defer
        />` in index.js or layout (for Next)?

**Comment by sulaimanwebdev** [comment] 2024-02-18 17:43
Temporarily I fixed it like this:

useEffect(() => {
    setTimeout(() => {
      // @ts-ignore
      window.createLemonSqueezy();
    }, 500);
  }, []);

**Comment by bmackio** [comment] 2024-02-18 17:51
Are you using a framework or vanilla html and js?

**Comment by bmackio** [comment] 2024-02-18 17:54
The reason why you haven't received an official response from lemon squeezy is probably because there's not enough information in your issue. If you copy and paste all your code, someone will be able to point you in the right direction. 

The maintainers also often ask for the ability to reproduce your error, so either creating an repo with all your code (or the relevant parts) or copy and pasting your code is required.

**Comment by bmackio** [comment] 2024-02-18 17:55
Also, if you feel like you fixed the issue, be sure to close the issue below, so it's not persisting as an open issue.

**Comment by bmackio** [comment] 2024-02-18 17:58
Here's a related issue: https://github.com/lmsqueezy/lemonsqueezy.js/issues/55

There's another npm package for client side. The one you're using, according to the other thread, was created for server side calls to the lemon squeezy API

**Comment by bmackio** [comment] 2024-02-18 17:59
https://docs.lemonsqueezy.com/help/lemonjs/what-is-lemonjs

**Closed** 2024-02-18 18:04 UTC

**Comment by de-mawo** [comment] 2024-08-18 19:18
> Temporarily I fixed it like this:
> 
> useEffect(() => { setTimeout(() => { // @ts-ignore window.createLemonSqueezy(); }, 500); }, []);

Hi @sulaimanwebdev  did you manage to get a different solution to the above? I got same error when using Checkout Overlays. The Docs are not straight forward on how to just implement checkout overlays

**Comment by brankoconjic** [comment] 2024-08-19 14:17
@de-mawo, if you are using Next.js there's an [example here](https://github.com/lmsqueezy/nextjs-billing/blob/44d85f03883aba3d6a6da13c1d94f7fdc2495cb8/src/app/dashboard/layout.tsx#L17-L21)

**Comment by de-mawo** [comment] 2024-08-21 14:34
> @de-mawo,
> 
> The library will initialize itself once the script has loaded.
> 
> Either ensure that the script is loaded before your components, or, if loaded afterwards, disable the button that opens the modal until the script is loaded and initialized.
> 
> If you are using Next.js, there's an [example here](https://github.com/lmsqueezy/nextjs-billing/blob/44d85f03883aba3d6a6da13c1d94f7fdc2495cb8/src/app/dashboard/layout.tsx#L17-L21) on how to load the script.
> 
> Also, see the [`signup-button.tsx`](https://github.com/lmsqueezy/nextjs-billing/blob/44d85f03883aba3d6a6da13c1d94f7fdc2495cb8/src/components/dashboard/billing/plans/signup-button.tsx) component on how to trigger the modal.
> 
> Let me know what you'd like to see in our docs to better help you get started with the checkout overlays.

Thank you this worked for me
